update test yml

diff --git a/.github/workflows/build-test-webapi.yml b/.github/workflows/build-test-webapi.yml
--- a/.github/workflows/build-test-webapi.yml
+++ b/.github/workflows/build-test-webapi.yml
@@ -45,8 +45,17 @@ jobs:
           working-directory: ./blotztask-test
 
         - name: Run tests
-          run: dotnet test --configuration Release --no-build --verbosity normal
+          run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
           working-directory: ./blotztask-test
+
+        - name: Test Report
+          uses: dorny/test-reporter@v1
+          if: success() || failure()    # Run even if tests fail
+          with:
+            name: .NET Test Results
+            path: '**/TestResults/*.trx'
+            reporter: dotnet-trx
+
 
         - name: Publish the project
           run: dotnet publish -c Release -o ${{ runner.temp }}/blotztask-api
